version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/api.Dockerfile
    env_file: ../../.env.example
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - qdrant
    volumes:
      - ../../services/api:/app/services/api
      - ../../packages:/app/packages
      - ../../configs:/app/configs

  worker:
    build:
      context: ../..
      dockerfile: infra/docker/worker.Dockerfile
    env_file: ../../.env.example
    depends_on:
      - db
      - redis
      - qdrant
    volumes:
      - ../../services/worker:/app/services/worker
      - ../../services/ai:/app/services/ai
      - ../../packages:/app/packages

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ai_edu
      POSTGRES_USER: ai_edu
      POSTGRES_PASSWORD: ai_edu
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.9.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  qdrant_data:
  minio_data:
